### ISSUE TITLE
Error getting LWA Access Token

### ISSUE THREAD

**Issue by 401009641** [amzn/selling-partner-api-docs#1085]
My account is authorized, but this exception occurs when I call it frequently：
java.lang.RuntimeException: Error getting LWA Access Token

	at com.amazon.spapi.SellingPartnerAPIAA.LWAClient.getAccessTokenFromEndpoint(LWAClient.java:70)
	at com.amazon.spapi.SellingPartnerAPIAA.LWAClient.getAccessTokenFromCache(LWAClient.java:47)
	at com.amazon.spapi.SellingPartnerAPIAA.LWAClient.getAccessToken(LWAClient.java:36)
	at com.amazon.spapi.SellingPartnerAPIAA.LWAAuthorizationSigner.sign(LWAAuthorizationSigner.java:69)
	at com.amazon.spapi.client.ApiClient.buildRequest(ApiClient.java:1041)
	at com.amazon.spapi.client.ApiClient.buildCall(ApiClient.java:980)
	at com.amazon.spapi.api.OrdersV0Api.getOrdersCall(OrdersV0Api.java:776)
	at com.amazon.spapi.api.OrdersV0Api.getOrdersValidateBeforeCall(OrdersV0Api.java:788)
	at com.amazon.spapi.api.OrdersV0Api.getOrdersWithHttpInfo(OrdersV0Api.java:839)
	at com.amazon.spapi.api.OrdersV0Api.getOrders(OrdersV0Api.java:814)
	at com.amazon.spapi.api.OrdersV0ApiTest.getOrdersTest(OrdersV0ApiTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:141)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.amazon.spapi.SellingPartnerAPIAA.LWAClient.getAccessTokenFromEndpoint(LWAClient.java:57)
	... 32 more
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:83)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:401)
		... 52 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 49 more

No problem if you request again：
![image](https://user-images.githubusercontent.com/20614254/125878773-c4c2ab5a-e7a3-49db-9bc6-92203e7fb02c.png)

**Comment by EpicTrollHa** [comment]
Hello, has your problem been solved? We also encountered the same problem and don't know how to deal with it.

**Comment by 401009641** [comment]
> 您好，您的问题解决了吗？我们也遇到了同样的问题，不知道如何处理。

Not yet  java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_291]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159) ~[na:1.8.0_291]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373) ~[na:1.8.0_291]

**Comment by 401009641** [comment]
> 您好，您的问题解决了吗？我们也遇到了同样的问题，不知道如何处理。

Not yet

**Comment by 401009641** [comment]
> 您好，您的问题解决了吗？我们也遇到了同样的问题，不知道如何处理。

Not yet  java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_291]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159) ~[na:1.8.0_291]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401) ~[na:1.8.0_291]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373) ~[na:1.8.0_291]

**Comment by 401009641** [comment]
Connection reset by peer: socket write error
![image](https://user-images.githubusercontent.com/20614254/126419417-207d8666-5a86-4c88-b046-e10ee7af841e.png)

**Comment by dongwenke0313** [comment]
I have some question，how to do? Save me!

**Comment by 401009641** [comment]
The official has not responded to me so far. In this case, I can only solve the problem by retrying the request. I made a retry mechanism in the OkHttp request of the underlying ApiClient

**Comment by 401009641** [comment]
> I have same question，how to do? Save me!

The official has not responded to me so far. In this case, I can only solve the problem by retrying the request. I made a retry mechanism in the OkHttp request of the underlying ApiClient
