### ISSUE TITLE
获取订单列表请求失败，这是哪里配置的不对呢，我是小白，刚开始对接

### ISSUE THREAD

**Issue by miaohouguo** [amzn/selling-partner-api-docs#1352]
------------------------------------------------------------
Response{protocol=http/1.1, code=403, message=Forbidden, url=https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER,A1AM78C64UM0Y8

-------------------------------------------------------------
10:23:57.470 [main] DEBUG com.amazonaws.auth.AWS4Signer - Generating a new signing key as the signing key not available in the cache for the date 1630627200000

io.swagger.client.ApiException: Forbidden

	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:974)
	at io.swagger.client.ApiClient.execute(ApiClient.java:890)
	at io.swagger.client.api.OrdersV0Api.getOrdersWithHttpInfo(OrdersV0Api.java:866)
	at io.swagger.client.api.OrdersV0Api.getOrders(OrdersV0Api.java:836)
	at io.swagger.client.api.SellersApiTest.getMarketplaceParticipationsTest(SellersApiTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

**Comment by hongtao0770** [comment]
Hi @miaohouguo,

It's also my first docking. Now I can successfully call the API to obtain data. What about a market call first?

**Comment by hongtao0770** [comment]
var resource = $"/orders/v0/orders";
            IRestRequest restRequest = new RestRequest(resource, Method.GET);
            restRequest.AddParameter("MarketplaceIds", MARKETPLACE_ID, ParameterType.QueryString);
            restRequest.AddParameter("CreatedAfter", DateTime.UtcNow.AddDays(-20).ToString("yyyy-MM-dd"), ParameterType.QueryString);
            restRequest.AddParameter("CreatedBefore", DateTime.UtcNow.ToString("yyyy-MM-dd"), ParameterType.QueryString);
            var client = new RestClient(this.Host);
            var credentials = new SellerAPICredentials();
            restRequest = SignWithAccessToken(restRequest, credentials.LWA_App_ClientId, credentials.LWA_App_ClientSecret, seller);
            restRequest = SignWithSTSKeysAndSecurityTokenn(restRequest, client.BaseUrl.Host, credentials.RoleARN, credentials.AWSKey, credentials.AWSSecret);
            IRestResponse response = client.Execute(restRequest);

**Comment by miaohouguo** [comment]
我是按这种方式测试的
OrdersV0Api ordersV0Api = new OrdersV0Api.Builder()
                .awsAuthenticationCredentials(awsAuthenticationCredentials)
                .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
                .awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
                .endpoint("https://sellingpartnerapi-na.amazon.com")
                .build();

       /* System.out.println(sellersApi.getMarketplaceParticipations());*/

        List<String> marketplaceIds =  Arrays.asList("ATVPDKIKX0DER","A1AM78C64UM0Y8");
        String createdAfter = "2021-06-11T16:08:08.868+08:00";
        String createdBefore ="2021-06-11T16:08:08.868+08:00";;
        String lastUpdatedAfter = "2021-06-11T16:08:08.868+08:00";;
        String lastUpdatedBefore = "2021-06-11T16:08:08.868+08:00";;
        List<String> orderStatuses = null;
        List<String> fulfillmentChannels = null;
        List<String> paymentMethods = null;
        String buyerEmail = null;
        String sellerOrderId = null;
        Integer maxResultsPerPage = null;
        List<String> easyShipShipmentStatuses = null;
        String nextToken = null;
        List<String> amazonOrderIds = null;
        String actualFulfillmentSupplySourceId = null;
        Boolean isISPU = null;
        String storeChainStoreId = null;
        GetOrdersResponse response = ordersV0Api.getOrders(marketplaceIds, createdAfter, createdBefore, lastUpdatedAfter, lastUpdatedBefore, orderStatuses, fulfillmentChannels, paymentMethods, buyerEmail, sellerOrderId, maxResultsPerPage, easyShipShipmentStatuses, nextToken, amazonOrderIds,actualFulfillmentSupplySourceId,isISPU,storeChainStoreId);
        System.out.println(response);
        // TODO: test validations

**Comment by hongtao0770** [comment]
Hi @miaohouguo,

If the Amazon parameter is wrong, the signature error will be returned. Please check whether the parameter format is correct.

Thanks.

**Comment by miaohouguo** [comment]
加个微信，交流一下miao1254447465

**Comment by wineloy** [comment]
Verify that you have added the session token in the "X-Amz-Security-Token" header and that it is signed in all your requests, remember that you must also have your "x-amz-access-token"
For more information I recommend that you read this website
https://marco-tibaldeschi.medium.com/amazon-sp-api-auth-auth-demystified-ab3bc746729b

**Comment by nodisk8800** [comment]
可以考虑加一下我们的技术QQ群,自己搜索一下

**Comment by miaohouguo** [comment]
> 可以考虑加一下我们的技术QQ群,自己搜索一下
多少呢我加一下

**Comment by miaohouguo** [comment]
> Verify that you have added the session token in the "X-Amz-Security-Token" header and that it is signed in all your requests, remember that you must also have your "x-amz-access-token" For more information I recommend that you read this website https://marco-tibaldeschi.medium.com/amazon-sp-api-auth-auth-demystified-ab3bc746729b

非常感谢，已经解决了

**Comment by avvarga** [comment]
Hello @miaohouguo,

Based on your last comment, it looks like this issue has been resolved.

I am closing this issue. Please feel free to reopen if necessary.

Regards,
Alejandro C.
SP API Developer Support

**Comment by wushao** [comment]
> 可以考虑加一下我们的技术QQ群，自己搜索一下

不好意思，借楼主贴子问一个问题。你好，我想请问一下，你清楚怎么调用SP-API进行Listing的停售吗
