### ISSUE TITLE
/fba/inventory/v1/summaries endpoint, response for some SellerSKUs return empty string for "lastUpdatedTime": "" 

### ISSUE THREAD

**Issue by midi-red** [amzn/selling-partner-api-docs#2063]
When requesting inventory summaries through SP-API /fba/inventory/v1/summaries endpoint, response for some SellerSKUs return empty string for "lastUpdatedTime": "" , which consequently causes Exception in SP-SPI

org.threeten.bp.format.DateTimeParseException: Text '' could not be parsed at index 0
at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1588)
at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
at org.threeten.bp.OffsetDateTime.parse(OffsetDateTime.java:359)
at com.amazon.sellingpartner.JSON$OffsetDateTimeTypeAdapter.read(JSON.java:215)
at com.amazon.sellingpartner.JSON$OffsetDateTimeTypeAdapter.read(JSON.java:179)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.Gson.fromJson(Gson.java:927)
at com.google.gson.Gson.fromJson(Gson.java:892)
at com.google.gson.Gson.fromJson(Gson.java:841)
at com.amazon.sellingpartner.JSON.deserialize(JSON.java:137)
at com.amazon.sellingpartner.ApiClient.deserialize(ApiClient.java:760)
at com.amazon.sellingpartner.ApiClient.handleResponse(ApiClient.java:963)
at com.amazon.sellingpartner.ApiClient.execute(ApiClient.java:890)
at com.amazon.sellingpartner.api.fbaInventory.FbaInventoryApi.getInventorySummariesWithHttpInfo(FbaInventoryApi.java:195)

Request Details:

x-amzn-RequestId: 20d2fea4-b3ce-4ca6-b8e6-cd60353b70c7
2022-02-20 09:36:25.045 DEBUG 41049 --- [ XNIO-1 task-1] com.amazonaws.auth.AWS4Signer : AWS4 Canonical Request: '"GET
/fba/inventory/v1/summaries
details=true&granularityId=ATVPDKIKX0DER&granularityType=Marketplace&marketplaceIds=ATVPDKIKX0DER&sellerSkus=OD%28FBA%29---561743
accept:application/json
content-type:application/json
host:sellingpartnerapi-na.amazon.com
user-agent:Swagger-Codegen/1.0.0/java
x-amz-access-token:Atza|IwEBIER5eigcR-kT....
x-amz-security-token:....

We opened a case:
ID 9664916671
We would appreciate help ASAP since this is causing interruptions in our APP.
@jevoniuk

**Comment by onebox24** [comment]
I also encounter this bug. Is there any easy workaround?

**Comment by smargoli2** [comment]
Still dealing with this, please advise

**Comment by Jookus** [comment]
Any news on this?

**Comment by midi-red** [comment]
I solved this isse by changing threeten package, compiled it and add it to my project separately. It is an ugly workaround but it looks like amazon has not fixed the issue.

**Comment by smargoli2** [comment]
@midi-red , Can you give more details? I am using C# so need more info for how to implement for myself...

**Comment by Jookus** [comment]
I finally found a workaround for the Java SDK, maybe that works for your sdks too? 

[Link](https://github.com/amzn/selling-partner-api-models/issues/291)

**Comment by daviddecorso** [comment]
Still an issue.
