### ISSUE TITLE
use Selling Partner API sandbox，response 400

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-docs#275]
Date: Thu, 07 Jan 2021 07:13:57 GMT
Content-Type: application/json
Content-Length: 79
Connection: keep-alive
x-amzn-RequestId: ad14f2db-ba7d-49b0-b1ab-84966c6a2f79
x-amz-apigw-id: YxEsUEiNoAMFhGw=
X-Amzn-Trace-Id: Root=1-5ff6b4b5-409111807fb39cc02365b30e;Sampled=0
OkHttp-Sent-Millis: 1610003637883
OkHttp-Received-Millis: 1610003638739

Exception in thread "main" io.swagger.client.ApiException: Bad Request
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:954)
	at io.swagger.client.ApiClient.execute(ApiClient.java:869)
	at io.swagger.client.api.FeedsApi.createFeedDocumentWithHttpInfo(FeedsApi.java:407)
	at io.swagger.client.api.FeedsApi.createFeedDocument(FeedsApi.java:393)
	at io.swagger.client.test.main(test.java:72)

**Comment by nodisk8800** [comment]
一些只读的数据,其实可以直接在生产环境里调用的,
这样可以避免一些额外的问题

**Comment by ShivikaK** [comment]
Hello @yan15195755798 

We will need to work with you via a support case to resolve this issue. Please open a support case so we can pursue the investigation.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello @yan15195755798 

As we havent received any response from you regarding this, I will close this issue.

Please open a support case with us for any errors with your sandbox requests and we can assist you further.

Thanks,
 Shivika Khare 
Selling Partner API Developer Support
